#pragma once

enum class Event {
	GAME_OVER,
	PLAYER_COLLIDE,
	PLAYER_HIT,
	PLAYER_DEAD,
	PLAYER_SPAWN,
	PLAYER_MOVE,
	PLAYER_PICKUP_ITEM,
	CHANGE_SCENE,
	PLAYER_SELECTED,
	AI_ADDED,
	GAME_PAUSED,
	APPLICATION_LOADED,
	GAME_START,
	OBJECT_INSTANTIATED,
	OBJECT_DESTROYED,
};